name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: utterance-deploy
        uses: jenkey2011/vuepress-deploy@master
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          TARGET_REPO: DNature/utterance
          TARGET_BRANCH: gh-pages
          BUILD_SCRIPT: yarn && yarn build && mv ./src/.vuepress/dist/ -t .
          BUILD_DIR: build/
